package com.myxh.mybatis.pojo;

public class Department
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_id
     *
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_name
     *
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.email
     *
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    private String email;

    public Department()
    {

    }

    public Department(Integer departmentId, String departmentName, String email)
    {
        this.departmentId = departmentId;
        this.departmentName = departmentName;
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_id
     *
     * @return the value of t_department.department_id
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public Integer getDepartmentId()
    {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_id
     *
     * @param departmentId the value for t_department.department_id
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public void setDepartmentId(Integer departmentId)
    {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_name
     *
     * @return the value of t_department.department_name
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public String getDepartmentName()
    {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_name
     *
     * @param departmentName the value for t_department.department_name
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public void setDepartmentName(String departmentName)
    {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.email
     *
     * @return the value of t_department.email
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public String getEmail()
    {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.email
     *
     * @param email the value for t_department.email
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public void setEmail(String email)
    {
        this.email = email == null ? null : email.trim();
    }

    @Override
    public String toString()
    {
        return "Department{" +
                "departmentId=" + departmentId +
                ", departmentName='" + departmentName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}