package com.myxh.mybatis.pojo;

public class Employee
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_id
     *
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    private Integer employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_name
     *
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.age
     *
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.gender
     *
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.email
     *
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.department_id
     *
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    private Integer departmentId;

    public Employee()
    {

    }

    public Employee(Integer employeeId, String employeeName, Integer age, String gender, String email, Integer departmentId)
    {
        this.employeeId = employeeId;
        this.employeeName = employeeName;
        this.age = age;
        this.gender = gender;
        this.email = email;
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_id
     *
     * @return the value of t_employee.employee_id
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public Integer getEmployeeId()
    {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_id
     *
     * @param employeeId the value for t_employee.employee_id
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public void setEmployeeId(Integer employeeId)
    {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_name
     *
     * @return the value of t_employee.employee_name
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public String getEmployeeName()
    {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_name
     *
     * @param employeeName the value for t_employee.employee_name
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public void setEmployeeName(String employeeName)
    {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.age
     *
     * @return the value of t_employee.age
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public Integer getAge()
    {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.age
     *
     * @param age the value for t_employee.age
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public void setAge(Integer age)
    {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.gender
     *
     * @return the value of t_employee.gender
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public String getGender()
    {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.gender
     *
     * @param gender the value for t_employee.gender
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public void setGender(String gender)
    {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.email
     *
     * @return the value of t_employee.email
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public String getEmail()
    {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.email
     *
     * @param email the value for t_employee.email
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public void setEmail(String email)
    {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.department_id
     *
     * @return the value of t_employee.department_id
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public Integer getDepartmentId()
    {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.department_id
     *
     * @param departmentId the value for t_employee.department_id
     * @mbggenerated Tue Aug 15 16:53:17 CST 2023
     */
    public void setDepartmentId(Integer departmentId)
    {
        this.departmentId = departmentId;
    }

    @Override
    public String toString()
    {
        return "Employee{" +
                "employeeId=" + employeeId +
                ", employeeName='" + employeeName + '\'' +
                ", age=" + age +
                ", gender='" + gender + '\'' +
                ", email='" + email + '\'' +
                ", departmentId=" + departmentId +
                '}';
    }
}